[project]
name = "sapphire-config"
version = "1.0.5"
description = "Sapphire Configuration Parser"
readme = "README.md"
license = "MIT"
license_files = [ "LICENCSE" ]
authors = [
    { name = "Todd Valentic", email = "todd.valentic@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "pytimeparse2>=1.7.1",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]


[project.urls]
Homepage="https://github.com/valentic/sapphire-config"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib"
]

[build-system]
requires = ["uv_build>=0.10.10,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.15.6",
]
